FROM debian:bookworm
MAINTAINER Sergey Ershov "ershovu@gmail.com"

ENV DEBIAN_FRONTEND noninteractive

ENTRYPOINT ["/opt/entrypoint.sh"]

RUN cd /tmp/ \
  && apt-get update -qy \
  && apt-get upgrade -qy \
# локаль
  && apt-get install -yqq  --no-install-recommends --no-install-suggests locales apt-utils

ENV LANG='ru_RU.UTF-8' LANGUAGE='ru_RU.UTF-8' LC_ALL='ru_RU.UTF-8'
RUN echo ru_RU.UTF-8 UTF-8 >> /etc/locale.gen && locale-gen

RUN cd /tmp/ \
 # timezone
  && ln -sf /usr/share/zoneinfo/Europe/Moscow  /etc/localtime && dpkg-reconfigure -f noninteractive tzdata \
 # install
  && apt-get update -qqy \
  && apt-get -y install \
    apache2 \
    php \
    php-mysql \
    php-ldap \
    php-xmlrpc \
    php-imap \
    curl \
    php-curl \
    php-gd \
    php-mbstring \
    php-xml \
    php-cas \
    php-zip \
    cron \
    rsyslog \
    wget \
    graphviz \
    php-snmp \
    php-intl \
    php-bz2 \
    php-cli
RUN cd /tmp/ \
  && apt-get update -qqy \
  && apt-get -y install gnupg2 \
  && apt-get -y --allow-unauthenticated install \
     lsb-release \
  ##
  && sed -i -e 's/^session.cookie_httponly.*/session.cookie_httponly = On/' `find / -name php.ini` \
  && sed -i -e 's/^;date\.timezone[[:space:]]=.*$/date.timezone = "Europe\/Moscow"/' `find / -name php.ini` \
  && sed -i -e 's/^memory_limit = .*/memory_limit = 1024M/' `find / -name php.ini` \
  ## clean
  && apt-get autoremove -qqy \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/*

COPY entrypoint.sh /opt/
RUN chmod +x /opt/entrypoint.sh
